### ISSUE TITLE
Building fails for Mac Arm64 

### ISSUE THREAD

**Issue by engie-tawfik** [skye-z/quest#5]
Hi Skye, 

 Following the readme to build from source for Mac arm64, the build fails as shown:
 
**modified build.sh to use mac arm64:**
<img width="941" alt="Screenshot 2024-08-23 at 21 22 19" src="https://github.com/user-attachments/assets/1033613c-1f43-4645-9b8c-37069c688eb0">

**started building:**
<img width="830" alt="Screenshot 2024-08-23 at 21 22 04" src="https://github.com/user-attachments/assets/b9658d31-3872-4312-a7db-b76986fe4e02">

As a workaround, I used the Mac arm64 binary from the release page, and it works well.

**Comment by skye-z** [comment]
hi, In order to be able to build a single product, I use embedding in main.go
```go
//go:embed page/error/* page/dist/*
var f embed.FS
```

So you need to build the front-end page before building the quest.

But that's an oversight on my part, I'll add a note to the readme, and a judgment call to build.sh.

**Comment by engie-tawfik** [comment]
Thank you so much! 🙏
