### ISSUE TITLE
Question character limit does not fit Google Cloud sample questions

### ISSUE THREAD

**Issue by engie-tawfik** [skye-z/quest#6]
Hi Skye,

 I am trying to build an easy practice exam for Google Professional Cloud Network Engineer ([PCNE](https://cloud.google.com/learn/certification/cloud-network-engineer)). All the questions planned for the practice are from [Google's sample questions form](https://docs.google.com/forms/d/e/1FAIpQLServ0tNGkr-dYAfmez_Gdk74dmVypZjzUKrkVFtFcArzhmPow/viewform).
 
 As shown below, the [question character limit](https://github.com/skye-z/quest-page/blob/main/src/components/modal/questionForm.vue#L8) does not allow pasting the full question from Google's sample.
 
 Can the question character limit be significantly increased in a new release, please?  
 
 **Question from Google sample:**
 
<img width="904" alt="Screenshot 2024-08-23 at 21 57 19" src="https://github.com/user-attachments/assets/dadad65d-c6b4-454e-9d77-2be19f3dea23">

 
 **Question pasted in quest:**
 
 
<img width="1512" alt="Screenshot 2024-08-23 at 21 40 25" src="https://github.com/user-attachments/assets/f3d36a8c-4cd4-4f50-8dcc-141be6f1e38d">

Thanks in advance!

**Comment by skye-z** [comment]
In the new version the limit has been raised to 2000 characters.

**Comment by engie-tawfik** [comment]
Many thanks! ❤️ 🥇 🤗
